# Deploy Sphinx.  This could be shorter, but we also do some extra
# stuff.
#
# License: CC-0.  This is the canonical location of this file, which
# you may want to link to anyway:
#   https://github.com/coderefinery/sphinx-lesson-template/blob/main/.github/workflows/sphinx.yml
#  https://raw.githubusercontent.com/coderefinery/sphinx-lesson-template/main/.github/workflows/sphinx.yml

name: sphinx
on: [push, pull_request]

env:
  DEFAULT_BRANCH: "rst-tryouts"
  # If these SPHINXOPTS are enabled, then be strict about the
  # builds and fail on any warnings.
  #SPHINXOPTS: "-W --keep-going -T"
  GENERATE_PDF: true          # to enable, must be 'true' lowercase
  GENERATE_SINGLEHTML: true   # to enable, must be 'true' lowercase
  PDF_FILENAME: singletCode.pdf
  MULTIBRANCH: true    # to enable, must be 'true' lowercase


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # https://github.com/marketplace/actions/setup-python
      # ^-- This gives info on matrix testing.
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      # https://docs.github.com/en/actions/guides/building-and-testing-python#installing-dependencies
      # ^-- This gives info on installing dependencies with pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        # Debug
      - name: Debugging information
        env:
          ref: ${{github.ref}}
          event_name: ${{github.event_name}}
          head_ref: ${{github.head_ref}}
          base_ref: ${{github.base_ref}}
        run: |
          echo "github.ref: ${ref}"
          echo "github.event_name: ${event_name}"
          echo "github.head_ref: ${head_ref}"
          echo "github.base_ref: ${base_ref}"
          echo "GENERATE_PDF: ${GENERATE_PDF}"
          echo "GENERATE_SINGLEHTML: ${GENERATE_SINGLEHTML}"
          set -x
          git rev-parse --abbrev-ref HEAD
          git branch
          git branch -a
          git remote -v
          python -V
          pip list --not-required
          pip list


      # Build
      - uses: ammaraskar/sphinx-problem-matcher@master
      - name: Build Sphinx docs (dirhtml)
        # SPHINXOPTS used via environment variables
        run: |
          cd ./docs/
          make dirhtml
          # This fixes broken copy button icons, as explained in
          #   https://github.com/coderefinery/sphinx-lesson/issues/50
          #   https://github.com/executablebooks/sphinx-copybutton/issues/110
          # This can be removed once these PRs are accepted (but the
          # fixes also need to propagate to other themes):
          #   https://github.com/sphinx-doc/sphinx/pull/8524
          #   https://github.com/readthedocs/sphinx_rtd_theme/pull/1025
          sed -i 's/url_root="#"/url_root=""/' _build/dirhtml/index.html || true

      # singlehtml
      - name: Generate singlehtml
        if: ${{ env.GENERATE_SINGLEHTML == 'true' }}
        run: |
          make singlehtml
          mv _build/singlehtml/ _build/dirhtml/singlehtml/

      # PDF if requested
      - name: Generate PDF
        if: ${{ env.GENERATE_PDF == 'true' }}
        run: |
          pip install https://github.com/rkdarst/sphinx_pyppeteer_builder/archive/refs/heads/main.zip
          make pyppeteer
          mv _build/pyppeteer/*.pdf _build/dirhtml/${PDF_FILENAME}

      